# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      brew update --quiet
      export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
      brew install hugo
      npm install -g npm
      npm install
    init: echo "Your version of Hugo is `hugo version`"
    command: cd hugo && hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview
