# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      brew install hugo
      npm install
      npm install avif
      brew install imagemagick@7
      alias xdg-open="$(which open)"
    init: echo "Your version of Hugo is `hugo version`"
    command: cd hugo && hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview
