# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup
    before: |
      export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
      brew install hugo
      alias ~="cd /workspace/rootwork.org"
      npm install
    init: echo "Your version of Hugo is `hugo version`"
    command: npm run gs

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 1313
    onOpen: open-preview
