baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Rootwork.org"
# googleAnalytics = ""
# disqusShortname = "rootwork"
theme = "aether-custom" # Forked from https://github.com/josephhutch/aether

[params]
  brand = "Rootwork.org"
  description = "Ivan Boothe develops digital strategy for nonprofits and social change."
  # homeimg = "Path, within the 'assets' folder, of the image used for the home button at the bottom of each post - optional"
  # bgimg = "Path, within the 'assets' folder, of the image used for the page background - optional"
  rssinmenu = "true"

[markup]
  [markup.highlight] # https://gohugo.io/getting-started/configuration-markup#highlight
    style = "monokai" # https://xyproto.github.io/splash/docs/all.html

# 
# DEPRECIATED
# -----------
# The params below this line are not actually being used; they're just for reference.
#

  # Header and navigation
  [params.header]
    title = "Ivan Boothe"
    shortBio = "Digital strategy for social change"

  # About section
  [params.about]
    title = "About me"
    bio = "**Ivan Boothe is a digital strategist grounded in social justice movements.**<br /><br />He specializes in Drupal, front-end development, social media strategy and online communications. His technical skills are firmly rooted in his background in on-the-ground social change and academic work in social movement history."

  # Contact secion
  [params.contact]
    title = "Contact"

    # The following social network icons are available:
    # 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
    # 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
    [[params.contact.social]]
      icon = "twitter"
      link = "//twitter.com/rootwork"

    [[params.contact.social]]
      icon = "github"
      link = "//github.com/rootwork"

    [[params.contact.social]]
      icon = "linkedin"
      link = "//www.linkedin.com/in/ivanboothe"

copyright = "Content licensed under [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Feel free to use or republish with credit! Image: Flickr user [Michar](https://www.flickr.com/photos/michar/2497651920/) (Creative Commons)."