[[main]]
  name = "Hello"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -109

# feeds

[[main]]
  name = "Feeds"
  identifier = "feeds"
  weight = -100

[[main]]
  parent = "feeds"
  name = "RSS"
  weight = 1
  url = "feed.rss"

[[main]]
  parent = "feeds"
  name = "Atom"
  weight = 2
  url = "feed.atom"

[[main]]
  parent = "feeds"
  name = "JSON feed"
  weight = 3
  url = "feed.json"

[[main]]
  parent = "feeds"
  name = "JF2 feed"
  weight = 4
  url = "jf2feed.json"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rootwork"
[[social]]
  name = "gitlab"
  type = "social"
  weight = 2
  url = "https://gitlab.com/rootwork"
[[social]]
  name = "codepen"
  type = "social"
  weight = 3
  url = "https://codepen.io/rootwork/"
[[social]]
  name = "drupal"
  type = "social"
  weight = 4
  url = "https://www.drupal.org/u/rootwork"
[[social]]
  name = "twitter"
  weight = 5
  url = "https://twitter.com/rootwork"
[[social]]
  name = "linkedin"
  weight = 6
  url = "https://www.linkedin.com/in/ivanboothe"

# other supported social links
# name = "youtube"
# url = ""
# name = "facebook"
# url = ""
# name = "instagram"
# url = ""
# name = "stackoverflow"
# url = ""
