[[main]]
  name = "Hello"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "Blog"
  url = "blog/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rootwork"
[[social]]
  name = "gitlab"
  type = "social"
  weight = 2
  url = "https://gitlab.com/rootwork"
[[social]]
  name = "codepen"
  type = "social"
  weight = 3
  url = "https://codepen.io/rootwork/"
[[social]]
  name = "drupal"
  type = "social"
  weight = 4
  url = "https://www.drupal.org/u/rootwork"
[[social]]
  name = "twitter"
  weight = 5
  url = "https://twitter.com/rootwork"
[[social]]
  name = "linkedin"
  weight = 6
  url = "https://www.linkedin.com/in/ivanboothe"
[[social]]
  name = "rss"
  weight = 7
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
