# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "/" # Include trailing slash
title = "Rootwork.org"
author = "Ivan Boothe" # Also set in [params.author]; defined here for safety

[module]
  [[module.imports]]
    path = "github.com/chipzoller/hugo-clarity" # Project theme

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

paginate = 10
canonifyurls = false # See https://gohugo.io/content-management/urls/#canonicalization

# Emoji
enableEmoji = true

# SEO settings
enableRobotsTXT = true
[sitemap]
  changefreq = "weekly"
  priority = 0.5

# [menus]
# config/_default/menus/menu.xx.toml

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
year = "year"
month = "month"

# RSS and search
[outputs]
   home = ["HTML", "RSS", "JSON"]
