baseurl = "https://rootwork.org/" # Include trailing slash
title = "Rootwork.org"
author = "Ivan Boothe" # Note in many places this is overridden by the data/authors.yml file

defaultContentLanguage = "en"
languageCode = "en-US"
timeZone = "America/Los_Angeles"
# [languages]
# config/_default/languages.toml

paginate = 10
canonifyurls = false # See https://gohugo.io/content-management/urls/#canonicalization
timeout = 30000
enableInlineShortcodes = true

# Emoji
enableEmoji = true

# Footnotes
footnoteReturnLinkContents = "^"

# Privacy settings

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.vimeo]
disable = false
enableDNT = true
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true

# SEO settings
enableRobotsTXT = true
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  # Priorities can be overridden using 'priority' in frontmatter
  # All pages and posts have a default priority of 0.6
  # All taxonomy lists have the default priority above, 0.5
  # Lists updated in the past year have a priority of 0.7
  # Pages and posts updated in the past year have a priority of 0.8
  # Pages and posts updated in the past month have a priority of 0.9
  # Home page has a priority of 1.0
  # See layouts/sitemap.xml for details.

# [menus]
# config/_default/menus/menu.xx.toml

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
year = "year"
month = "month"

# Define feeds and search formats
[outputs]
  home = ["HTML", "JSON", "RSS", "ATOM", "JF2Feed"]
  # <domain>/posts/jf2feed.json
  # section = ["HTML", "RSS", "JF2Feed"]  # default = ["HTML", "RSS"]
  # <domain>/posts/mypost/jf2post.json
  # page = ["HTML", "JF2Post"]            # default = ["HTML"]

# Define feed output formats
[outputFormats]
  [outputFormats.Rss]
    mediaType = "application/rss+xml"
    baseName = "feed"

  [outputFormats.Atom]
    mediaType = "application/atom+xml"
    baseName = "feed"

  [outputFormats.JF2Feed]
    mediaType = "application/jf2feed+json"
    baseName = "jf2feed" # generated file = <baseName>.<mediaType."application/jf2feed+json".suffixes[0]> = jf2feed.json
    isPlainText = true

# Define feed media types
[mediaTypes]

  [mediaTypes."application/atom+xml"]
    suffixes = ["atom"]

  [mediaTypes."application/rss+xml"]
    suffixes = ["rss"]

  [mediaTypes."application/jf2feed+json"]
    suffixes = ["json"]

# Always minify, but exclude feed data
# See: https://jdheyburn.co.uk/blog/who-goes-blogging-7-hugo-minify-rss-code-indentation-fix/
[minify]
  disableXML = true
  minifyOutput = true
