baseurl = "https://rootwork.github.io/rootwork.org/" # Include trailing slash
title = "Rootwork.org"
author = "Ivan Boothe" # Also set in [params.author]; defined here for safety

defaultContentLanguage = "en"
languageCode = "en-US"
# [languages]
# config/_default/languages.toml

paginate = 10
canonifyurls = false # See https://gohugo.io/content-management/urls/#canonicalization
timeout = 30000
enableInlineShortcodes = true

# Emoji
enableEmoji = true

# Footnotes

footnoteReturnLinkContents = "^"

# Privacy settings

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.vimeo]
disable = false
enableDNT = true
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true

# SEO settings
enableRobotsTXT = true
[sitemap]
  changefreq = "weekly"
  priority = 0.5

# [menus]
# config/_default/menus/menu.xx.toml

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
year = "year"
month = "month"

# Define feeds and search formats
[outputs]
  home = ["HTML", "RSS", "ATOM", "JSON"]

# Define feed output formats
[outputFormats]

  [outputFormats.ATOM]
  name = "ATOM"
  baseName = "feed"
  mediaType = "application/atom+xml"

# Define feed media types
[mediaTypes]

  [mediaTypes."application/atom+xml"]
  suffixes = ["atom"]
