timeout = 30000
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = false
simple = true

[privacy.twitter]
disable = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.vimeo]
disable = false
enableDNT = true
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true
