name: Publish Hugo site to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Node dependencies
        # The first line of `run` is designed to omit husky setup, since it's
        # not necessary or desireable in a remote build.
        run: |
          npm pkg set scripts.prepare=" "
          npm ci
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build Hugo site
        # `npm run p` optimizes images and then builds the site, copying over
        # the optimized images. `git restore` then removes the optimized images
        # from the repo, leaving them only in the public site.
        run: |
          npm run p -- --baseUrl https://rootwork.github.io/rootwork.org/
          git restore hugo/content
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo/public
